version: '3'
services:
  frontend:
    image: node:latest
    env_file:
      - .env
    volumes:
      - ./:/app
    entrypoint: [sh, -c, 'cd /app && rm -rf .next && yarn && yarn dev']
  nginx:
    image: nginx:alpine
    tty: true
    env_file:
      - .env
    depends_on:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - ${FRONTEND_PORT}:80
